version: 2

# Zensical build, per https://docs.readthedocs.com/platform/latest/intro/zensical.html
build:
  os: ubuntu-lts-latest
  tools:
    python: latest
  jobs:
    install:
      - pip install -r docs/_requirements.txt
      - pip install .
    build:
      html:
        - zensical build
    post_build:
      - mkdir -p $READTHEDOCS_OUTPUT/html/
      - cp --recursive site/* $READTHEDOCS_OUTPUT/html/
